name: initial_white_label
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  tap_debouncer: ^2.0.2
  cached_network_image: ^3.2.2
  styled_widget: ^0.4.0+3
  json_serializable: ^6.4.0
  injectable: ^2.1.2
  get_it: ^7.2.0
  auto_route: ^5.0.1
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.0.15
  flutter_screenutil: ^5.5.4
  flutter_secure_storage: ^8.0.0
  flutter_rest_client:
  change_app_package_name: ^1.1.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  carousel_slider: ^4.2.1
  firebase_core: ^2.14.0
  hydrated_bloc: ^9.1.2
  path_provider: ^2.0.15   
  master_ui_collection:
  firebase_auth: ^4.6.3
  loading_animation_widget: ^1.2.0+4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_maps_flutter: ^2.4.0
  geolocator: ^9.0.2
  custom_marker: ^1.0.0
  firebase_messaging: ^14.6.5
  socket_io_client: ^2.0.3
  permission_handler: ^10.4.3  
  flutter_chat_bubble: ^2.0.2
  flutter_local_notifications: ^15.1.1
  intl: ^0.18.1
  webview_flutter: ^4.2.4
  json_annotation: ^4.8.1
  in_app_update: ^4.2.1
  social_login_bloc: ^0.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.10+1
  flutter_gen_runner:
  build_runner: ^2.3.3
  injectable_generator: ^2.1.6
  auto_route_generator: ^5.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  jwt_decode: ^0.3.1
  hive_generator: ^2.0.0


flutter_gen:
  integrations:
    flutter_svg: true
  colors:
    inputs:
      - assets/colors/color.xml

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/poppins/
    - assets/fonts/source_sans_pro/
    - assets/fonts/open_sans/
 
  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins/poppins_thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/poppins_extralight.ttf
          weight: 200
        - asset: assets/fonts/poppins/poppins_light.ttf
          weight: 300
        - asset: assets/fonts/poppins/poppins_regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/poppins_medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/poppins_semibold.ttf
          weight: 600
        - asset: assets/fonts/poppins/poppins_bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/poppins_extrabold.ttf
          weight: 800
        - asset: assets/fonts/poppins/poppins_black.ttf
          weight: 900
        - asset: assets/fonts/poppins/poppins_thinitalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/poppins/poppins_extralightitalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/poppins/poppins_lightitalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/poppins/poppins_italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/poppins/poppins_mediumitalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins/poppins_semibolditalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/poppins/poppins_bolditalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/poppins/poppins_extrabolditalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/poppins/poppins_blackitalic.ttf
          weight: 900
          style: italic
    - family: Source Sans Pro
      fonts:
        - asset: assets\fonts\source_sans_pro\SourceSansPro-Regular.ttf

    - family: OpenSans
      fonts:
        - asset: assets\fonts\open_sans\OpenSans-Bold.ttf
        - asset: assets\fonts\open_sans\OpenSans-BoldItalic.ttf
        - asset: assets\fonts\open_sans\OpenSans-ExtraBold.ttf
        - asset: assets\fonts\open_sans\OpenSans-ExtraBoldItalic.ttf
        - asset: assets\fonts\open_sans\OpenSans-Italic.ttf
        - asset: assets\fonts\open_sans\OpenSans-Light.ttf
        - asset: assets\fonts\open_sans\OpenSans-LightItalic.ttf
        - asset: assets\fonts\open_sans\OpenSans-Medium.ttf
        - asset: assets\fonts\open_sans\OpenSans-MediumItalic.ttf
        - asset: assets\fonts\open_sans\OpenSans-Regular.ttf
        - asset: assets\fonts\open_sans\OpenSans-SemiBold.ttf
        - asset: assets\fonts\open_sans\OpenSans-SemiBoldItalic.ttf
        - asset: assets\fonts\open_sans\OpenSans_Condensed-Bold.ttf
        - asset: assets\fonts\open_sans\OpenSans_Condensed-BoldItalic.ttf
        - asset: assets\fonts\open_sans\OpenSans_Condensed-ExtraBold.ttf
        - asset: assets\fonts\open_sans\OpenSans_Condensed-ExtraBoldItalic.ttf
        - asset: assets\fonts\open_sans\OpenSans_Condensed-Italic.ttf
        - asset: assets\fonts\open_sans\OpenSans_Condensed-Light.ttf
        - asset: assets\fonts\open_sans\OpenSans_Condensed-LightItalic.ttf
        - asset: assets\fonts\open_sans\OpenSans_Condensed-Medium.ttf
        - asset: assets\fonts\open_sans\OpenSans_Condensed-MediumItalic.ttf
        - asset: assets\fonts\open_sans\OpenSans_Condensed-Regular.ttf
        - asset: assets\fonts\open_sans\OpenSans_Condensed-SemiBold.ttf
        - asset: assets\fonts\open_sans\OpenSans_Condensed-SemiBoldItalic.ttf
        - asset: assets\fonts\open_sans\OpenSans_SemiCondensed-Bold.ttf
        - asset: assets\fonts\open_sans\OpenSans_SemiCondensed-BoldItalic.ttf
        - asset: assets\fonts\open_sans\OpenSans_SemiCondensed-ExtraBold.ttf
        - asset: assets\fonts\open_sans\OpenSans_SemiCondensed-ExtraBoldItalic.ttf
        - asset: assets\fonts\open_sans\OpenSans_SemiCondensed-Italic.ttf
        - asset: assets\fonts\open_sans\OpenSans_SemiCondensed-Light.ttf
        - asset: assets\fonts\open_sans\OpenSans_SemiCondensed-LightItalic.ttf
        - asset: assets\fonts\open_sans\OpenSans_SemiCondensed-Medium.ttf
        - asset: assets\fonts\open_sans\OpenSans_SemiCondensed-MediumItalic.ttf
        - asset: assets\fonts\open_sans\OpenSans_SemiCondensed-Regular.ttf
        - asset: assets\fonts\open_sans\OpenSans_SemiCondensed-SemiBold.ttf
        - asset: assets\fonts\open_sans\OpenSans_SemiCondensed-SemiBoldItalic.ttf
   
